/**
 * This file has a dictionary (object) that links the abbriviation that Catena
 * assigns to every book of the Bible to the full name of the book.
 * The abbriviation is the key and the full name is the value.
 */

const catenaBookNames = {
	////////////////////////////////////////////////////////
	//                  Old Testament
	////////////////////////////////////////////////////////
	gn: "Genesis",
	ex: "Exodus",
	lv: "Leviticus",
	nm: "Numbers",
	dt: "Deuteronomy",
	jo: "Joshua",
	jgs: "Judges",
	ru: "Ruth",
	"1sm": "1 Samuel",
	"2sm": "2 Samuel",
	"1kgs": "1 Kings",
	"2kgs": "2 Kings",
	"1chr": "1 Chronicles",
	"2chr": "2 Chronicles",
	"1esd": "1 Esdras",
	ezr: "Ezra",
	neh: "Nehemiah",
	tb: "Tobit",
	jdt: "Judith",
	est: "Esther",
	"1mc": "Maccabees 1",
	"2mc": "Maccabees 2",
	ps: "Psalms",
	jb: "Job",
	prv: "Proverbs",
	eccl: "Ecclesiastes",
	sg: "Song of Songs",
	ws: "Wisdom of Solomon",
	sir: "Wisdom of Sirach",
	hos: "Hosea",
	am: "Amos",
	mi: "Micah",
	jl: "Joel",
	ob: "Obadiah",
	jon: "Jonah",
	na: "Nahum",
	hb: "Habakkuk",
	zep: "Zephaniah",
	hg: "Haggai",
	zec: "Zechariah",
	mal: "Malachi",
	is: "Isaiah",
	jer: "Jeremiah",
	bar: "Baruch",
	eoj: "Epistle of Jeremiah",
	lam: "Lamentations",
	ez: "Ezekiel",
	dn: "Daniel",
	////////////////////////////////////////////////////////
	//                  New Testament
	////////////////////////////////////////////////////////

	mt: "Matthew",
	mk: "Mark",
	lk: "Luke",
	jn: "John",
	acts: "Acts",
	rom: "Romans",
	"1cor": "1 Corinthians",
	"2cor": "2 Corinthians",
	gal: "Galatians",
	eph: "Ephesians",
	phil: "Philippians",
	col: "Colossians",
	"1thes": "1 Thessalonians",
	"2thes": "2 Thessalonians",
	"1tm": "1 Timothy",
	"2tm": "2 Timothy",
	ti: "Titus",
	phlm: "Philemon",
	heb: "Hebrews",
	jas: "James",
	"1pt": "1 Peter",
	"2pt": "2 Peter",
	"1jn": "1 John",
	"2jn": "2 John",
	"3jn": "3 John",
	jude: "Jude",
	rv: "Revelation",
};

export default catenaBookNames;

// TODO change this to have the number of chapters of each book
export const chaptersPerBook = {
	////////////////////////////////////////////////////////
	//                  Old Testament
	////////////////////////////////////////////////////////
	gn: "Genesis",
	ex: "Exodus",
	lv: "Leviticus",
	nm: "Numbers",
	dt: "Deuteronomy",
	jo: "Joshua",
	jgs: "Judges",
	ru: "Ruth",
	"1sm": "1 Samuel",
	"2sm": "2 Samuel",
	"1kgs": "1 Kings",
	"2kgs": "2 Kings",
	"1chr": "1 Chronicles",
	"2chr": "2 Chronicles",
	"1esd": "1 Esdras",
	ezr: "Ezra",
	neh: "Nehemiah",
	tb: "Tobit",
	jdt: "Judith",
	est: "Esther",
	"1mc": "Maccabees 1",
	"2mc": "Maccabees 2",
	ps: "Psalms",
	jb: "Job",
	prv: "Proverbs",
	eccl: "Ecclesiastes",
	sg: "Song of Songs",
	ws: "Wisdom of Solomon",
	sir: "Wisdom of Sirach",
	hos: "Hosea",
	am: "Amos",
	mi: "Micah",
	jl: "Joel",
	ob: "Obadiah",
	jon: "Jonah",
	na: "Nahum",
	hb: "Habakkuk",
	zep: "Zephaniah",
	hg: "Haggai",
	zec: "Zechariah",
	mal: "Malachi",
	is: "Isaiah",
	jer: "Jeremiah",
	bar: "Baruch",
	eoj: "Epistle of Jeremiah",
	lam: "Lamentations",
	ez: "Ezekiel",
	dn: "Daniel",
	////////////////////////////////////////////////////////
	//                  New Testament
	////////////////////////////////////////////////////////

	mt: "Matthew",
	mk: "Mark",
	lk: "Luke",
	jn: "John",
	acts: "Acts",
	rom: "Romans",
	"1cor": "1 Corinthians",
	"2cor": "2 Corinthians",
	gal: "Galatians",
	eph: "Ephesians",
	phil: "Philippians",
	col: "Colossians",
	"1thes": "1 Thessalonians",
	"2thes": "2 Thessalonians",
	"1tm": "1 Timothy",
	"2tm": "2 Timothy",
	ti: "Titus",
	phlm: "Philemon",
	heb: "Hebrews",
	jas: "James",
	"1pt": "1 Peter",
	"2pt": "2 Peter",
	"1jn": "1 John",
	"2jn": "2 John",
	"3jn": "3 John",
	jude: "Jude",
	rv: "Revelation",
};
