/**
 * This file has a dictionary (object) that links the abbriviation that Catena
 * assigns to every book of the Bible to the full name of the book.
 * The abbriviation is the key and the full name is the value.
 */

const catenaBookNames = {
	////////////////////////////////////////////////////////
	//                  Old Testament
	////////////////////////////////////////////////////////
	gn: "Genesis",
	ex: "Exodus",
	lv: "Leviticus",
	nm: "Numbers",
	dt: "Deuteronomy",
	jo: "Joshua",
	jgs: "Judges",
	ru: "Ruth",
	"1sm": "1 Samuel",
	"2sm": "2 Samuel",
	"1kgs": "1 Kings",
	"2kgs": "2 Kings",
	"1chr": "1 Chronicles",
	"2chr": "2 Chronicles",
	ezr: "Ezra",
	neh: "Nehemiah",
	tb: "Tobit",
	jdt: "Judith",
	est: "Esther",
	"1mc": "Maccabees 1",
	"2mc": "Maccabees 2",
	ps: "Psalms",
	jb: "Job",
	prv: "Proverbs",
	eccl: "Ecclesiastes",
	sg: "Song of Songs",
	ws: "Wisdom of Solomon",
	sir: "Wisdom of Sirach",
	hos: "Hosea",
	am: "Amos",
	mi: "Micah",
	jl: "Joel",
	ob: "Obadiah",
	jon: "Jonah",
	na: "Nahum",
	hb: "Habakkuk",
	zep: "Zephaniah",
	hg: "Haggai",
	zec: "Zechariah",
	mal: "Malachi",
	is: "Isaiah",
	jer: "Jeremiah",
	bar: "Baruch",
	lam: "Lamentations",
	ez: "Ezekiel",
	dn: "Daniel",
	////////////////////////////////////////////////////////
	//                  New Testament
	////////////////////////////////////////////////////////

	mt: "Matthew",
	mk: "Mark",
	lk: "Luke",
	jn: "John",
	acts: "Acts",
	rom: "Romans",
	"1cor": "1 Corinthians",
	"2cor": "2 Corinthians",
	gal: "Galatians",
	eph: "Ephesians",
	phil: "Philippians",
	col: "Colossians",
	"1thes": "1 Thessalonians",
	"2thes": "2 Thessalonians",
	"1tm": "1 Timothy",
	"2tm": "2 Timothy",
	ti: "Titus",
	phlm: "Philemon",
	heb: "Hebrews",
	jas: "James",
	"1pt": "1 Peter",
	"2pt": "2 Peter",
	"1jn": "1 John",
	"2jn": "2 John",
	"3jn": "3 John",
	jude: "Jude",
	rv: "Revelation",
};

export default catenaBookNames;

// TODO change this to have the number of chapters of each book
export const chaptersPerBook = {
	////////////////////////////////////////////////////////
	//                  Old Testament
	////////////////////////////////////////////////////////
	gn: 50,
	ex: 40,
	lv: 27,
	nm: 26,
	dt: 34,
	jo: 24,
	jgs: 21,
	ru: 4,
	"1sm": 31,
	"2sm": 24,
	"1kgs": 22,
	"2kgs": 25,
	"1chr": 29,
	"2chr": 36,
	ezr: 10,
	neh: 13,
	tb: 14,
	jdt: 16,
	est: 10,
	"1mc": 16,
	"2mc": 15,
	ps: 150,
	jb: 42,
	prv: 31,
	eccl: 12,
	sg: 8,
	ws: 19,
	sir: 51,
	hos: 14,
	am: 9,
	mi: 7,
	jl: 3,
	ob: 1,
	jon: 4,
	na: 3,
	hb: 3,
	zep: 3,
	hg: 2,
	zec: 14,
	mal: 4,
	is: 66,
	jer: 52,
	bar: 6,
	lam: 5,
	ez: 48,
	dn: 14,
	////////////////////////////////////////////////////////
	//                  New Testament
	////////////////////////////////////////////////////////

	mt: 28,
	mk: 16,
	lk: 24,
	jn: 21,
	acts: 28,
	rom: 16,
	"1cor": 16,
	"2cor": 13,
	gal: 6,
	eph: 6,
	phil: 4,
	col: 4,
	"1thes": 5,
	"2thes": 3,
	"1tm": 6,
	"2tm": 4,
	ti: 3,
	phlm: 1,
	heb: 13,
	jas: 5,
	"1pt": 5,
	"2pt": 3,
	"1jn": 5,
	"2jn": 1,
	"3jn": 1,
	jude: 1,
	rv: 22,
};
